raft_topology: fence RPCs when transitioning to tokens_state::read_write
gleb-cloudius/scylla pull request #1
Opened 2022-12-12 10:34 UTC by gusev-p

The patch introduces the concept of topology version,
an int which is incremented when the topology state
changes. It's used to catch and block with error the RPCs
which were issued based on the old topology version
when the cluster is transitioning to the new one.

The patch adds topology version handling to the storage proxy.
The main function try_apply_fence compares the version
from the RPC parameters with the current one. If the version
from the parameters is greater than the current version, we
wait for the topology update on the current node
(wait_for_next_version). If the version from the parameters is
less than the current version, and the range no longer belongs
to the current node, an exception is thrown. At the moment,
this exception causes the original request to fail, in the future
the code will be improved so that the original request is
retried on the new topology.

2022-12-12 11:14 UTC, gleb-cloudius requested changes

2022-12-12 11:14 UTC, gleb-cloudius commented on db/system_keyspace.cc
> +future<service::topology_state_ptr> system_keyspace::load_topology_state() {
I introduced `topology_type `exactly so that the type could be changed without changing it at every place it is used.

2022-12-12 11:14 UTC, gleb-cloudius commented on locator/token_metadata.cc
> +        if (version != _topology_version && version != _topology_version + 1) {
How can we guaranty that each node sees every version? We cannot. The version cannot go backwards, but since we re-create token_metadata from scratch each time new state is received we cannot check even this here. May be we can if clean() does not reset it.

2022-12-12 11:14 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
Why did you remove `fence_old_reads` command. Why do you thin it is not needed?

2022-12-12 11:14 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        throw stale_fencing_token(caller_token, fencing_token{current_topology_version});
It is better to not use exception to return results.

2022-12-12 11:14 UTC, gleb-cloudius commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
I would rather put the version as a static column in topology table.

2022-12-12 11:14 UTC, gleb-cloudius commented on service/storage_service.cc
> +                // In this state writes goes to old and new replicas but reads with old versions will be fenced out.
So here you suppose to wait for old reads to complete before moving to the next state , but you dropped the rpc. Why?

2022-12-12 11:14 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        // todo abort_source?
Timeout at least.

2022-12-12 11:14 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        current_topology_version = _shared_token_metadata.get()->get_topology_version();
Here` current_topology_version` may jump to be greater than `caller_token.topology_version` and you need to execute the `if` above again.

2022-12-12 11:14 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            co_await _sp.check_fencing_token(*fencing_token);
In case the check fails here we need to go slow path and check that the token for the request still belongs to this node and proceed if yes.

We also cannot just abandon the write here. A writer will never know what happened to it and will wait for it until timeout. We need to send MUTATION_FAILED with new type of error so that the writer will first know that there is no point to wait for a reply and second that it needs to retry the write (in the future).

2022-12-13 08:50 UTC, gusev-p reviewed
current todos:
  *check_token -> read RPC
  *check_token slow path, proceed if the token belongs to this node
  * MUTATION_FAILED,  just fail for now? wait for new topology
  *check_token: current_topology_version may jump to be greater than caller_token.topology_version

2022-12-13 08:50 UTC, gusev-p commented on db/system_keyspace.cc
> +future<service::topology_state_ptr> system_keyspace::load_topology_state() {
ok, will revert

2022-12-13 08:50 UTC, gusev-p commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
static column=something attached to partition key, topology table is partitioned by raft_id, i.e. node id, but what we need is one global number for the entire topology

2022-12-13 08:50 UTC, gusev-p commented on locator/token_metadata.cc
> +        if (version != _topology_version && version != _topology_version + 1) {
fixed

2022-12-13 08:50 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
we do `raft_bootstrap_cmd::command::barrier` before transitioning to `tokens_state::owner`, this means all the nodes received `tokens_state::read_write` with new version and hence already fenced old reads (there is no code for the read RPC right now, but it's the same as for mutation, i'll add it)

2022-12-13 08:50 UTC, gusev-p commented on service/storage_proxy.cc
> +            co_await _sp.check_fencing_token(*fencing_token);
> In case the check fails here we need to go slow path and check that the token for the request still belongs to this node and proceed if yes.

Yes, skipped that for the first iteration, will add.

> We also cannot just abandon the write here. A writer will never know what happened to it and will wait for it until timeout. We need to send MUTATION_FAILED with new type of error so that the writer will first know that there is no point to wait for a reply and second that it needs to retry the write (in the future).

Yes, missed that, will add.

2022-12-13 08:50 UTC, gusev-p commented on service/storage_proxy.cc
> +        throw stale_fencing_token(caller_token, fencing_token{current_topology_version});
ok

2022-12-13 08:50 UTC, gusev-p commented on service/storage_proxy.cc
> +        current_topology_version = _shared_token_metadata.get()->get_topology_version();
ok

2022-12-13 08:50 UTC, gusev-p commented on service/storage_service.cc
> +                // In this state writes goes to old and new replicas but reads with old versions will be fenced out.
we do `raft_bootstrap_cmd::command::barrier` above, that means no new reads with old version can start. I put off the logic with waiting for inflight reads for now as it seem second priority, we can add it later, or just retry the RPCs. After some thought, waiting for readers here does not seem like a great idea to me, since we can wait for quite a long or indefinite time, and this is a rather fragile design.

2022-12-13 09:20 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
The difference between `barrier` and `fence_old_reads` is that later returns only after there is no reads with old topology running any more (or at least it tries to guaranty it). This way we can reduce window when rpc fencing causes errors. A replica may still answer to reads with old version while its own fence_old_reads did not complete yet. I agree that now `barrier` and `fence_old_reads` are the same, but they will not be.

2022-12-13 09:21 UTC, gleb-cloudius commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
static column is not attached to a partition key. It is global per table.

2022-12-13 09:24 UTC, gleb-cloudius commented on service/storage_service.cc
> +                // In this state writes goes to old and new replicas but reads with old versions will be fenced out.
Of course we should not wait without timeout. Today we would wait for a read timeout since it is global for all requests. When/if we will have per request timeout we can still wait for some reasonable max value. It is not crucial  that we wait for all of them since we have RPC fencing to handle those that we missed.

2022-12-13 09:26 UTC, gusev-p commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
https://docs.scylladb.com/stable/cql/ddl.html#static-columns

> Some columns can be declared as STATIC in a table definition. A column that is static will be “shared” by all the rows belonging to the same partition (having the same [partition key](https://docs.scylladb.com/stable/cql/ddl.html#partition-key)).

2022-12-13 09:35 UTC, gleb-cloudius commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
Ah, right. I confused clustering and partition key here. We can change the table schema to have one partition and host id to be a clustering key. But OTOH that means we will have single partition and I am not sure how large it will grow. OK, lets keep it in scylla_local at least for now.

2022-12-13 14:27 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
It seems the algorithm should look something like this:
1. `raft_apply(tokens_state=ReadWrite, version=current_version+1, migrating=true)`; migrating means check_fencing_token won't throw on both current_version+1 and current_version. If after step 1 check_fencing_token accept only the new version (like it is in the current version of the code), we will end with error all RPCs for the moving token ranges for the duration of step 2, which makes no sense.
2. `barrier`. This ensures all nodes in the cluster:
  * use current_version+1 to send RPCs;
  * mutations go to old and new replicas, reads go to new replicas;
3. `raft_apply(tokens_state=owned, migrating=false)`. To get an error here an RPC must be quite lucky:
  * it must come to old replica with a token of the moved ranges;
  * it must be issued by the sender node before that node received the updated topology in steps 1-2 and it must reach the target node after step 3, i.e. it has travelled the wire for the duration steps 1-2.

  Suppose there were two nodes S and T. Node S was the coordinator for a read op for some token from the moving token range and it was the last one we reached with the new topology in step 2. Node T was the old replica for the moving token range and it was the first one we reached in step 3. Then the error scenario should be:
  * S issues read RPC to T;
  * S gets update from step 1-2;
  * T gets update from step 3;
  * T received read RPC from S.

  It's possible, but it seems the probability (and the number of such RPCs) should be small. We can just fence/retry these unlucky RPCs for now. We can later add `fence_all_reads` before step 3 to wait for all reads with prev version to finish.

2022-12-13 14:32 UTC, gusev-p commented on service/storage_service.cc
> +                // In this state writes goes to old and new replicas but reads with old versions will be fenced out.
Wrote the arguments above that `fence_all_reads` can be useful in very specific and rare cases.

2022-12-13 14:57 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
Instead of `bool migrating` we can bump version on both `ReadWrite` and `owned` and for odd versions `check_fencing_token` should accept the previous one.

2022-12-13 15:41 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
Why having  `migrating` is this better than having `fence_all_reads` rpc that will work as I described? Also if we do plan to add it it is better to have it from the beginning even doing nothing because it will be easier to upgrade later.

I do not think it will work as well though. Suppose we have a node A with old range that received current_ver + 1 and accepts current_ver as well for the range. After all nodes moved to current_ver + 1 some of them moved to current_ver + 2 and stopped writing into the A. But there still can be an old read in the system to A  with  current_ver and it will be answered and may miss recent writes. 

Now, for that two happen, assuming all nodes are alive the read should have been started before those writes and technically it is legal to return stale data. But at some point we want to allow topology changes only with quorum (or at least with some nodes down, this is supported today) and in this case a read request may be coming from a node that restarted and its request should be fenced.

2022-12-13 15:43 UTC, gleb-cloudius commented on db/system_keyspace.cc
> +mutation system_keyspace::make_scylla_local_param_mutation(int64_t ts, const sstring& key, data_value&& value) {
Single partition will be easier to transfer in a snapshot though. Well, may be later.

2022-12-13 16:13 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
Actually we need fence_writes instead of the barrier as well. We have to make sure that all old write either completed or will fail befoe we start streaming, so we will ahve to increase version twice first  when we move to read_only and then read_write. Writes are even more serious than reads.

2022-12-14 07:50 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
> After all nodes moved to current_ver + 1 some of them moved to current_ver + 2 and stopped writing into the A. But there still can be an old read in the system to A with current_ver and it will be answered and may miss recent writes.

This is exactly the scenario I mentioned on the call, you said it't not a problem.

> But at some point we want to allow topology changes only with quorum (or at least with some nodes down, this is supported today) and in this case a read request may be coming from a node that restarted and its request should be fenced.

I don't quite understand, how we can relieve the barrier requirement that all nodes are up. Basically, what we need is to guarantee that when the step 3 above started, no stale reads can happen. Now it's simple - we know that all the nodes are using the new topology, so no stale reads are possible. If we up to allow barrier to skip some nodes (e.g. if they are inaccessible due to temporarily connectivity problems), then no guarantees can be made, regardless of whether we accept previous version or not.

Maybe instead of all nodes being up we can demand that only nodes, 'affected' by the topology change operation to be up. If that's the case, and we managed to update the topology version on those nodes to the new one and fence all the previous versions, this could work.

> This way we can reduce window when rpc fencing causes errors. A replica may still answer to reads with old version while its own fence_old_reads did not complete yet. 

I don't understand, how it's supposed to work. We update the version though RAFT, as soon as the replica applies the raft command, it will start fencing old requests and this can happen before `fence_old_reads` reaches it.

2022-12-14 08:31 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
> > After all nodes moved to current_ver + 1 some of them moved to current_ver + 2 and stopped writing into the A. But there still can be an old read in the system to A with current_ver and it will be answered and may miss recent writes.
> 
> This is exactly the scenario I mentioned on the call, you said it't not a problem.

I acknowledge that in my reply as well "Now, for that two happen, assuming all nodes are alive the read should have been started before those writes and technically it is legal to return stale data". But then there was "but" there.

But for write it is not the case! Writes that started before streaming started have to fail. So write_only state needs to do write fencing before start streaming, not just a barrier. The reason for that is this:

Suppose we have replicas A, B, C for a range R and now A moves the range to joining node D. There is a write W from node B that started before streaming and before B learned that D is joining. The write uses quorum consistency and has replicas A, B, C. Before the write reached A the barrier completed and streaming started. Streaming moved range R to D and only after that the write reached A. A acked it. B acked it. On C the write failed. Write succeeded because it has quorum of replies, but from new replica set B, C, D only B has the data breaking consistency guaranties.

> 
> > But at some point we want to allow topology changes only with quorum (or at least with some nodes down, this is supported today) and in this case a read request may be coming from a node that restarted and its request should be fenced.
> 
> I don't quite understand, how we can relieve the barrier requirement that all nodes are up. Basically, what we need is to guarantee that when the step 3 above started, no stale reads can happen. Now it's simple - we know that all the nodes are using the new topology, so no stale reads are possible. If we up to allow barrier to skip some nodes (e.g. if they are inaccessible due to temporarily connectivity problems), then no guarantees can be made, regardless of whether we accept previous version or not.

Yes, exactly what I was saying. For that use case we need more strict fencing.

> 
> Maybe instead of all nodes being up we can demand that only nodes, 'affected' by the topology change operation to be up. If that's the case, and we managed to update the topology version on those nodes to the new one and fence all the previous versions, this could work.

With ring it will be practically always the case that all nodes are affected. With tablets yes, we may require all the nodes affected by moving of one range has to be up, but if we can do without why not?

> 
> > This way we can reduce window when rpc fencing causes errors. A replica may still answer to reads with old version while its own fence_old_reads did not complete yet.
> 
> I don't understand, how it's supposed to work. We update the version though RAFT, as soon as the replica applies the raft command, it will start fencing old requests and this can happen before `fence_old_reads` reaches it.

The replica will start fencing old requests not when new version arrives through raft, but only when it completes its own `fence_old_reads`. Until then it will take ver and ver + 1 reads.

2022-12-14 10:48 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
> Yes, exactly what I was saying. For that use case we need more strict fencing.

The point was, without full cluster-wide barrier (or at least affected nodes barrier) we can't guarantee anything, no matter how 'strict' our fencing is.

> The replica will start fencing old requests not when new version arrives through raft, but only when it completes its own fence_old_reads. Until then it will take ver and ver + 1 reads.

we need two broadcast calls, IIUC:
1. `raft_apply(tokens_state=ReadWrite, version=current_version+1)` accept current_version+1 and current_version, store this fact only in memory
2. `wait_all_completed(timeout=several seconds)`, run on all nodes, read_barrier on each, wait for outgoing RPCs with old version to finish
3. `fence`, run on all nodes, start to fence old RPCs
4. `raft_apply(tokens_state=owned)`. Here we need that either there are no nodes using old topology for sending RPCs _or_ no nodes accepting old topology (these requirements are pretty much the same in terms of the end result). If both 2 and 3 above have run successfully on all nodes, we have both. What if they failed, or some nodes are inaccessible from this node (but accesible from others)? For example, if we can't reach nodes A and B, A is an old owner of some range R and B can reach A, then there can be arbitrary writes to R on A during step 4, which will be missed.

2022-12-14 12:08 UTC, gusev-p commented on service/raft_bootstrap.hh
> +          stream_ranges
Regarding tablets, again, IIUC, tablet is a range with it's own RAFT group on top of it. The main difference from the ring is that we can leverage the correlation between quorums of regular read/write operations and topology change operations, akin to what we do in RAFT itself for modify_config. Actually, if we have a tablet with tree nodes A, B and C, and we decide to move it from C to D, we can just use modify_config, no?

2022-12-14 12:42 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +          stream_ranges
> Regarding tablets, again, IIUC, tablet is a range with it's own RAFT group on top of it. The main difference from the ring is that we can leverage the correlation between quorums of regular read/write operations and topology change operations, akin to what we do in RAFT itself for modify_config. Actually, if we have a tablet with tree nodes A, B and C, and we decide to move it from C to D, we can just use modify_config, no?

Only for "replace" kind of operations. But tablet topology operations will split tablets between different groups or move just some ranges. There will be a period of where two tablets will be responsible for a range.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        });
If a nice argument trick does not work any more I'd rather have `remote::receive_hint_mutation_handler` member function like any other verb.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/raft_bootstrap.hh
> +    int64_t topology_version;
Will a single version be enough considering that we first want to do write fencing without fencing reads and then fence reads without fencing writes?

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +
Why did you need to move it? Looks like it is used much later then currently defined.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto pending_endpoints = erm->get_token_metadata_ptr()->pending_endpoints_for(request_info.token, ks_name);
Nit: if it is const, it can as well be a reference.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
Why not just pass a schema and token instead of having the function to retrieve it? Creating the function requires allocation.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            rpc::optional<fencing_token> fencing_token, std::optional<partition_key_view> partition_key,
Instead of  partition_key here you can have a function template that, given `in`, returns its key. BTW why is it optional?

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        if (errors.count == 0) {
This indentation change is impossible to review. This is usually handled by leaving the wrong indent after adding the if() and having a follow up patch that changes indent and states that nothing have changed but indent.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        return _mutation_holder->apply_remotely(*_proxy, ep, std::move(forward), response_id, timeout, std::move(tr_state), _rate_limit_info, fencing_token{_effective_replication_map_ptr->get_token_m
There can be preemption point between `mutation_holder` creation and calling of  `apply_remotely`. The version should be part of the holder itself.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +                    return send_mutation(addr, timeout, std::move(trace_info), m, {}, reply_to, shard, response_id, rate_limit_info, fence ? *fence: fencing_token{0});
Isn't it a problem to send zero here unless it is handles specially.

2022-12-27 14:08 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +        return _mutation_holder->apply_remotely(*_proxy, ep, std::move(forward), response_id, timeout, std::move(tr_state), _rate_limit_info, fencing_token{_effective_replication_map_ptr->get_token_m
Or may be _effective_replication_map_ptr holds for us the original version of token_metadata... Then it is fine.

2023-01-11 17:42 UTC, gusev-p commented
created a new PR over the master https://github.com/scylladb/scylladb/pull/12500

2023-01-11 17:42 UTC, gusev-p commented on service/raft_bootstrap.hh
> +    int64_t topology_version;
Didn't give it much thought yet. This PR is about the initial impl of fencing in storage service. I will address this in the next PR, the one about linking all this with the topology state machine.

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +
True, the code changed several times, this is not needed, reverted

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +        });
ok, done

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +            rpc::optional<fencing_token> fencing_token, std::optional<partition_key_view> partition_key,
> Instead of partition_key here you can have a function template that, given in, returns its key.

done

> BTW why is it optional?

no reason, fixed

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +        if (errors.count == 0) {
use can use this

<img width="409" alt="image" src="https://user-images.githubusercontent.com/6216459/211797440-0811ca5d-b764-4ac6-8550-9973227481c3.png">

or similar option in your diff viewer

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +        if (errors.count == 0) {
> This is usually handled by leaving the wrong indent after adding the if() and having a follow up patch that changes indent and states that nothing have changed but indent.

this is a lot of manual work that are easy to miss. This is what we actually end up with in this snippet: `try` was not properly indented before this patch

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +                    return send_mutation(addr, timeout, std::move(trace_info), m, {}, reply_to, shard, response_id, rate_limit_info, fence ? *fence: fencing_token{0});
null `fencing_token` would be during upgrade, when not all nodes have been upgraded yet. If we (upgraded node) convert it to zero (we received mutation from not yet upgraded node) and the target node is already updated and have bigger version, it will throw and RPC would fail. We should make `service::fencing_token` explicitly optional, this will turn it to `rpc::optional<std::optional<fencing_token>> fencing_token`, similar to trace_info, but this is probably fine.

ok, will fix it.

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +        return _mutation_holder->apply_remotely(*_proxy, ep, std::move(forward), response_id, timeout, std::move(tr_state), _rate_limit_info, fencing_token{_effective_replication_map_ptr->get_token_m
> Or may be _effective_replication_map_ptr holds for us the original version of token_metadata... Then it is fine.

yes, exactly

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
In `handle_write` we will block on `get_schema_for_write` before `forward_fn`, now they run in parallel.

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto pending_endpoints = erm->get_token_metadata_ptr()->pending_endpoints_for(request_info.token, ks_name);
ok

2023-01-11 17:42 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
`noncopyable_function` is inplace if the func is no more that 4 bytes, here we have only a couple of refs

2023-01-12 09:20 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> In `handle_write` we will block on `get_schema_for_write` before `forward_fn`, now they run in parallel.

I do not understand what are you trying to say here. Before your patch they run in parallel indeed. After your patch it looks like they do not, but what does it have to do with my original comment?

2023-01-12 09:23 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> `noncopyable_function` is inplace if the func is no more that 4 bytes, here we have only a couple of refs

The interface does not limit the size of the function. Also a ref is 8 bytes. I am not against the interface if it provides some benefit, I just do not understand yet what the benefit is.

2023-01-12 10:02 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> > In `handle_write` we will block on `get_schema_for_write` before `forward_fn`, now they run in parallel.
> 
> I do not understand what are you trying to say here. Before your patch they run in parallel indeed. After your patch it looks like they do not, but what does it have to do with my original comment?

They won't run in parallel if we eagerly obtain the schema before `try_apply_fence`. The schema is only needed in the rare case when the versions don't match. By employing function here we obtain the schema only when needed, allowing for parallelism in most cases.

2023-01-12 10:04 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> > `noncopyable_function` is inplace if the func is no more that 4 bytes, here we have only a couple of refs
> 
> The interface does not limit the size of the function. Also a ref is 8 bytes. I am not against the interface if it provides some benefit, I just do not understand yet what the benefit is.

confused bits and bytes) 32 bytes, of couse

2023-01-12 10:07 UTC, gusev-p commented
close in favour of https://github.com/scylladb/scylladb/pull/12500

2023-01-12 10:07 UTC, closed without merging

2023-01-12 10:23 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> > > In `handle_write` we will block on `get_schema_for_write` before `forward_fn`, now they run in parallel.
> > 
> > 
> > I do not understand what are you trying to say here. Before your patch they run in parallel indeed. After your patch it looks like they do not, but what does it have to do with my original comment?
> 
> They won't run in parallel if we eagerly obtain the schema before `try_apply_fence`. The schema is only needed in the rare case when the versions don't match. By employing function here we obtain the schema only when needed, allowing for parallelism in most cases.

OK. I see what you mean. Obtaining the schema is also rare, It is usually noop, so it is an optimization on an optimization. So why not call `get_schema_for_write()` from `try_apply_fence` directly? The second call for it in the `write_fn` will do nothing since it will find the schema in the registry already. You do not need to cache it by yourself.

2023-01-12 10:47 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> OK. I see what you mean. Obtaining the schema is also rare, It is usually noop, so it is an optimization on an optimization. So why not call `get_schema_for_write()` from `try_apply_fence` directly? The second call for it in the `write_fn` will do nothing since it will find the schema in the registry already. You do not need to cache it by yourself.

Is there any difference between `get_schema_for_read` and `get_schema_for_write`? Now they are used separately for read and write code path, but implementation of these functions is the same. That's what stopped me from proceeding as you described initially.

2023-01-12 10:53 UTC, gleb-cloudius commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
> > OK. I see what you mean. Obtaining the schema is also rare, It is usually noop, so it is an optimization on an optimization. So why not call `get_schema_for_write()` from `try_apply_fence` directly? The second call for it in the `write_fn` will do nothing since it will find the schema in the registry already. You do not need to cache it by yourself.
> 
> Is there any difference between `get_schema_for_read` and `get_schema_for_write`? Now they are used separately for read and write code path, but implementation of these functions is the same. That's what stopped me from proceeding as you described initially.

There was a difference once. Now one calls another but we decided to leave the names for documentation purposes. Even if there was a difference `try_apply_fence` can be split to `try_apply_read_fence` and `try_apply_write_fence`.

2023-01-16 12:55 UTC, gusev-p commented on service/storage_proxy.cc
> +            const auto request_info = co_await get_request_info();
refactored this all a bit, please have a look at a newer version of this PR [here](https://github.com/scylladb/scylladb/pull/12500/files)